#[derive(Debug, Default, Copy, Clone)]
pub enum Buildings {
    #[default]
    Default, // means standard buildings built by default
    HordePlaceholder8,
    HordePlaceholder7,
    HordePlaceholder6,
    HordePlaceholder5,
    HordePlaceholder4,
    HordePlaceholder3,
    HordePlaceholder2,
    HordePlaceholder1,
    Nothing,
    MagesGuild1,
    MagesGuild2,
    MagesGuild3,
    MagesGuild4,
    MagesGuild5,
    Tavern,
    Shipyard,
    Fort,
    Citadel,
    Castle,
    VillageHall,
    TownHall,
    CityHall,
    Capitol,
    Marketplace,
    ResourceSilo,
    Blacksmith,
    Special1,
    Horde1,
    Horde1Upgr,
    Ship,
    // Special2,
    // Special3,
    Special4,
    Horde2,
    Horde2Upgr,
    Grail,
    ExtraTownHall,
    ExtraCityHall,
    ExtraCapitol,
    DwellFirst,
    DwellLvl2,
    DwellLvl3,
    DwellLvl4,
    DwellLvl5,
    DwellLvl6,
    // DwellLast,
    // DwellUpFirst,
    DwellLvl2Up,
    DwellLvl3Up,
    DwellLvl4Up,
    DwellLvl5Up,
    DwellLvl6Up,
    // DwellUpLast,
    DwellLvl8,
    DwellLvl8Up,
    DwellLvl1,
    DwellLvl7,
    DwellLvl1Up,
    DwellLvl7Up,
    // DwellUp2First,
    //Special buildings for towns.
    CastleGate,       //Inferno
    FreelancersGuild, //Stronghold
    ArtifactMerchant,
    DecodeError,
}

impl Buildings {
    pub fn from(code: i32) -> Self {
        use Buildings::*;
        match code {
            -50 => Default,
            -37 => HordePlaceholder8,
            -36 => HordePlaceholder7,
            -35 => HordePlaceholder6,
            -34 => HordePlaceholder5,
            -33 => HordePlaceholder4,
            -32 => HordePlaceholder3,
            -31 => HordePlaceholder2,
            -30 => HordePlaceholder1,
            -1 => Nothing,
            0 => MagesGuild1,
            1 => MagesGuild2,
            2 => MagesGuild3,
            3 => MagesGuild4,
            4 => MagesGuild5,
            5 => Tavern,
            6 => Shipyard,
            7 => Fort,
            8 => Citadel,
            9 => Castle,
            10 => VillageHall,
            11 => TownHall,
            12 => CityHall,
            13 => Capitol,
            14 => Marketplace,
            15 => ResourceSilo,
            16 => Blacksmith,
            // 17 => Special1,
            17 => ArtifactMerchant,
            18 => Horde1,
            19 => Horde1Upgr,
            20 => Ship,
            // 21 => Special2,
            21 => FreelancersGuild, // Stringhold
            // 22 => Special3,
            22 => CastleGate, // inferno
            23 => Special4,
            24 => Horde2,
            25 => Horde2Upgr,
            26 => Grail,
            27 => ExtraTownHall,
            28 => ExtraCityHall,
            29 => ExtraCapitol,
            // 30 =>   DwellFirst ,
            30 => DwellLvl1,
            31 => DwellLvl2,
            32 => DwellLvl3,
            33 => DwellLvl4,
            34 => DwellLvl5,
            35 => DwellLvl6,
            36 => DwellLvl7,
            // 36 =>    DwellLast ,
            // 37 => DwellUpFirst,
            37 => DwellLvl1Up,
            38 => DwellLvl2Up,
            39 => DwellLvl3Up,
            40 => DwellLvl4Up,
            41 => DwellLvl5Up,
            42 => DwellLvl6Up,
            // 43 =>   DwellUpLast ,
            43 => DwellLvl7Up,
            // 44 => DwellUp2First ,
            150 => DwellLvl8,
            151 => DwellLvl8Up,
            // DwellFirst =>   ,
            // DwellLast =>   ,
            // DwellUpFirst =>   ,
            // DwellUpLast =>   ,
            // DwellLvl7Up + 1 =>   ,
            // Special3 => ,       //Inferno
            // Special2 => , //Stronghold
            // Special1 => ,
            _ => DecodeError,
        }
    }
}
